export type Locale = 'zh-CN' | 'en';
export type Localized = Record<Locale,string>;
export const markets = [{code:'CN',enabled:true,locales:['zh-CN','en'],currency:'CNY'}];
export const productCatalog = ['GFRP Rebar','BFRP Rebar','CFRP Rebar','GFRP Mesh','GFRP Rockbolt','FRP reinforcement products'];
export interface Project {id:string;market:string;name:Localized;buyer:Localized;province:string;application:string;relevance:'high'|'medium';deadline:string;discovered:string;source:string;products:string[];budget:string|null}
export const projects:Project[] = [
 {id:'CN-2026-001',market:'CN',name:{'zh-CN':'深圳机场扩建工程',en:'Shenzhen Airport Expansion'},buyer:{'zh-CN':'深圳机场建设单位（模拟）',en:'Shenzhen Airport Project Authority (mock)'},province:'guangdong',application:'airport',relevance:'high',deadline:'2026-11-10',discovered:'2026-09-30',source:'gov',products:['GFRP Rebar','GFRP Mesh'],budget:'¥ 280,000,000'},
 {id:'CN-2026-002',market:'CN',name:{'zh-CN':'上海地铁隧道建设项目',en:'Shanghai Metro Tunnel Project'},buyer:{'zh-CN':'上海轨道交通建设单位（模拟）',en:'Shanghai Transit Project Authority (mock)'},province:'shanghai',application:'tunnel',relevance:'high',deadline:'2026-10-28',discovered:'2026-09-29',source:'public',products:['GFRP Rockbolt','GFRP Rebar'],budget:null},
 {id:'CN-2026-003',market:'CN',name:{'zh-CN':'浙江沿海防护工程',en:'Zhejiang Coastal Protection Works'},buyer:{'zh-CN':'浙江海岸工程建设单位（模拟）',en:'Zhejiang Coastal Works Authority (mock)'},province:'zhejiang',application:'marine',relevance:'medium',deadline:'2026-11-18',discovered:'2026-09-28',source:'provincial',products:['BFRP Rebar','GFRP Mesh'],budget:'¥ 96,000,000'},
 {id:'CN-2026-004',market:'CN',name:{'zh-CN':'江苏跨海桥梁加固工程',en:'Jiangsu Coastal Bridge Reinforcement'},buyer:{'zh-CN':'江苏交通工程建设单位（模拟）',en:'Jiangsu Transport Project Authority (mock)'},province:'jiangsu',application:'bridge',relevance:'high',deadline:'2026-10-22',discovered:'2026-09-26',source:'public',products:['GFRP Rebar','BFRP Rebar','CFRP Rebar'],budget:'¥ 165,000,000'},
 {id:'CN-2026-005',market:'CN',name:{'zh-CN':'山东高速公路改扩建工程',en:'Shandong Highway Upgrade'},buyer:{'zh-CN':'山东公路建设单位（模拟）',en:'Shandong Highway Project Authority (mock)'},province:'shandong',application:'highway',relevance:'medium',deadline:'2026-11-05',discovered:'2026-09-24',source:'gov',products:['GFRP Rebar','GFRP Mesh'],budget:null},
 {id:'CN-2026-006',market:'CN',name:{'zh-CN':'四川地下综合管廊工程',en:'Sichuan Underground Utility Corridor'},buyer:{'zh-CN':'四川市政建设单位（模拟）',en:'Sichuan Municipal Project Authority (mock)'},province:'sichuan',application:'underground',relevance:'high',deadline:'2026-11-24',discovered:'2026-09-20',source:'construction',products:['GFRP Rebar','FRP reinforcement products'],budget:'¥ 72,000,000'},
 {id:'CN-2026-007',market:'CN',name:{'zh-CN':'湖北水利枢纽修复项目',en:'Hubei Water Infrastructure Restoration'},buyer:{'zh-CN':'湖北水务建设单位（模拟）',en:'Hubei Water Project Authority (mock)'},province:'hubei',application:'water',relevance:'medium',deadline:'2026-12-02',discovered:'2026-09-18',source:'provincial',products:['BFRP Rebar','GFRP Mesh'],budget:null},
 {id:'CN-2026-008',market:'CN',name:{'zh-CN':'山西矿山支护工程',en:'Shanxi Mining Support Project'},buyer:{'zh-CN':'山西矿山建设单位（模拟）',en:'Shanxi Mining Project Authority (mock)'},province:'shanxi',application:'mining',relevance:'high',deadline:'2026-11-30',discovered:'2026-09-15',source:'public',products:['GFRP Rockbolt'],budget:null}
];
export const provinceStats=[{key:'guangdong',value:32},{key:'shanghai',value:24},{key:'zhejiang',value:21},{key:'jiangsu',value:18},{key:'shandong',value:15},{key:'other',value:18}];
export const applicationStats=[{key:'tunnel',value:29},{key:'bridge',value:25},{key:'marine',value:23},{key:'highway',value:19},{key:'water',value:14},{key:'underground',value:11},{key:'mining',value:7}];
export const competitorData=[{id:'pulwell',name:'Pulwell',update:'pulwellUpdate',time:'hours2',color:'#3978e7'},{id:'manufacturer',name:'manufacturer',update:'manufacturerUpdate',time:'hours5',color:'#e6a744'},{id:'composite',name:'composite',update:'compositeUpdate',time:'day1',color:'#30a88a'}];
export const materialAliases:Record<string,string[]>={'GFRP Rebar':['玻璃纤维增强复合材料筋','玻璃纤维','玻纤筋','corrosion-resistant reinforcement','耐腐蚀增强材料'],'BFRP Rebar':['玄武岩纤维','玄武岩筋'],'CFRP Rebar':['碳纤维','碳纤维筋'],'GFRP Mesh':['玻纤网格','FRP Mesh','网格'],'GFRP Rockbolt':['玻璃纤维锚杆','锚杆'],'FRP reinforcement products':['复合增强材料']};
